# Generated by Django 4.0.4 on 2022-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcn',
            name='phone',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
